/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * NetworkRoutesApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_NetworkRoutesApi_H_
#define IO_SWAGGER_CLIENT_API_NetworkRoutesApi_H_


#include "../ApiClient.h"

#include "NetworkTypeDTO.h"

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  NetworkRoutesApi
{
public:
    NetworkRoutesApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~NetworkRoutesApi();
    /// <summary>
    /// Get the current network type of the chain
    /// </summary>
    /// <remarks>
    /// Returns the current network type.
    /// </remarks>
    pplx::task<std::shared_ptr<NetworkTypeDTO>> getNetworkType(
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_NetworkRoutesApi_H_ */

