/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * NodeRoutesApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_NodeRoutesApi_H_
#define IO_SWAGGER_CLIENT_API_NodeRoutesApi_H_


#include "../ApiClient.h"

#include "NodeInfoDTO.h"
#include "NodeTimeDTO.h"

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  NodeRoutesApi
{
public:
    NodeRoutesApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~NodeRoutesApi();
    /// <summary>
    /// Get the node information
    /// </summary>
    /// <remarks>
    /// Supplies additional information about the application running on a [Node](https://nemtech.github.io/concepts/node.html).
    /// </remarks>
    pplx::task<std::shared_ptr<NodeInfoDTO>> getNodeInfo(
    );
    /// <summary>
    /// Get the node time
    /// </summary>
    /// <remarks>
    /// Supplies additional information about the application running on a node.
    /// </remarks>
    pplx::task<std::shared_ptr<NodeTimeDTO>> getNodeTime(
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_NodeRoutesApi_H_ */

