/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * AccountInfoDTO.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_AccountInfoDTO_H_
#define IO_SWAGGER_CLIENT_MODEL_AccountInfoDTO_H_


#include "../ModelBase.h"

#include "AccountMetaDTO.h"
#include "AccountDTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  AccountInfoDTO
    : public ModelBase
{
public:
    AccountInfoDTO();
    virtual ~AccountInfoDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AccountInfoDTO members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AccountMetaDTO> getMeta() const;
        void setMeta(std::shared_ptr<AccountMetaDTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AccountDTO> getAccount() const;
        void setAccount(std::shared_ptr<AccountDTO> value);

protected:
    std::shared_ptr<AccountMetaDTO> m_Meta;
        std::shared_ptr<AccountDTO> m_Account;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_AccountInfoDTO_H_ */
