/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Addresses.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Addresses_H_
#define IO_SWAGGER_CLIENT_MODEL_Addresses_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Addresses
    : public ModelBase
{
public:
    Addresses();
    virtual ~Addresses();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Addresses members

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getAddresses();
    bool addressesIsSet() const;
    void unsetAddresses();
    void setAddresses(std::vector<utility::string_t> value);

protected:
    std::vector<utility::string_t> m_Addresses;
    bool m_AddressesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Addresses_H_ */
