/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "AnnounceTransactionInfoDTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

AnnounceTransactionInfoDTO::AnnounceTransactionInfoDTO()
{
    m_Message = utility::conversions::to_string_t("");
}

AnnounceTransactionInfoDTO::~AnnounceTransactionInfoDTO()
{
}

void AnnounceTransactionInfoDTO::validate()
{
    // TODO: implement validation
}

web::json::value AnnounceTransactionInfoDTO::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("message")] = ModelBase::toJson(m_Message);

    return val;
}

void AnnounceTransactionInfoDTO::fromJson(web::json::value& val)
{
    setMessage(ModelBase::stringFromJson(val[utility::conversions::to_string_t("message")]));
}

void AnnounceTransactionInfoDTO::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("message"), m_Message));
}

void AnnounceTransactionInfoDTO::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setMessage(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("message"))));
}

utility::string_t AnnounceTransactionInfoDTO::getMessage() const
{
    return m_Message;
}


void AnnounceTransactionInfoDTO::setMessage(utility::string_t value)
{
    m_Message = value;
    
}
}
}
}
}

