/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BlockDTO.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_BlockDTO_H_
#define IO_SWAGGER_CLIENT_MODEL_BlockDTO_H_


#include "../ModelBase.h"

#include "UInt64DTO.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  BlockDTO
    : public ModelBase
{
public:
    BlockDTO();
    virtual ~BlockDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BlockDTO members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSignature() const;
        void setSignature(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSigner() const;
        void setSigner(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    double getVersion() const;
        void setVersion(double value);
    /// <summary>
    /// 
    /// </summary>
    double getType() const;
        void setType(double value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getHeight() const;
        void setHeight(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getTimestamp() const;
        void setTimestamp(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getDifficulty() const;
        void setDifficulty(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPreviousBlockHash() const;
        void setPreviousBlockHash(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBlockTransactionsHash() const;
        void setBlockTransactionsHash(utility::string_t value);

protected:
    utility::string_t m_Signature;
        utility::string_t m_Signer;
        double m_Version;
        double m_Type;
        std::shared_ptr<UInt64DTO> m_Height;
        std::shared_ptr<UInt64DTO> m_Timestamp;
        std::shared_ptr<UInt64DTO> m_Difficulty;
        utility::string_t m_PreviousBlockHash;
        utility::string_t m_BlockTransactionsHash;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_BlockDTO_H_ */
