/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "BlockchainScoreDTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

BlockchainScoreDTO::BlockchainScoreDTO()
{
}

BlockchainScoreDTO::~BlockchainScoreDTO()
{
}

void BlockchainScoreDTO::validate()
{
    // TODO: implement validation
}

web::json::value BlockchainScoreDTO::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("scoreHigh")] = ModelBase::toJson(m_ScoreHigh);
    val[utility::conversions::to_string_t("scoreLow")] = ModelBase::toJson(m_ScoreLow);

    return val;
}

void BlockchainScoreDTO::fromJson(web::json::value& val)
{
    std::shared_ptr<UInt64DTO> newScoreHigh(new UInt64DTO());
    newScoreHigh->fromJson(val[utility::conversions::to_string_t("scoreHigh")]);
    setScoreHigh( newScoreHigh );
    std::shared_ptr<UInt64DTO> newScoreLow(new UInt64DTO());
    newScoreLow->fromJson(val[utility::conversions::to_string_t("scoreLow")]);
    setScoreLow( newScoreLow );
}

void BlockchainScoreDTO::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    m_ScoreHigh->toMultipart(multipart, utility::conversions::to_string_t("scoreHigh."));
    m_ScoreLow->toMultipart(multipart, utility::conversions::to_string_t("scoreLow."));
}

void BlockchainScoreDTO::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    std::shared_ptr<UInt64DTO> newScoreHigh(new UInt64DTO());
    newScoreHigh->fromMultiPart(multipart, utility::conversions::to_string_t("scoreHigh."));
    setScoreHigh( newScoreHigh );
    std::shared_ptr<UInt64DTO> newScoreLow(new UInt64DTO());
    newScoreLow->fromMultiPart(multipart, utility::conversions::to_string_t("scoreLow."));
    setScoreLow( newScoreLow );
}

std::shared_ptr<UInt64DTO> BlockchainScoreDTO::getScoreHigh() const
{
    return m_ScoreHigh;
}


void BlockchainScoreDTO::setScoreHigh(std::shared_ptr<UInt64DTO> value)
{
    m_ScoreHigh = value;
    
}
std::shared_ptr<UInt64DTO> BlockchainScoreDTO::getScoreLow() const
{
    return m_ScoreLow;
}


void BlockchainScoreDTO::setScoreLow(std::shared_ptr<UInt64DTO> value)
{
    m_ScoreLow = value;
    
}
}
}
}
}

