/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "BlockInfoDTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

BlockInfoDTO::BlockInfoDTO()
{
}

BlockInfoDTO::~BlockInfoDTO()
{
}

void BlockInfoDTO::validate()
{
    // TODO: implement validation
}

web::json::value BlockInfoDTO::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("meta")] = ModelBase::toJson(m_Meta);
    val[utility::conversions::to_string_t("block")] = ModelBase::toJson(m_Block);

    return val;
}

void BlockInfoDTO::fromJson(web::json::value& val)
{
    std::shared_ptr<BlockMetaDTO> newMeta(new BlockMetaDTO());
    newMeta->fromJson(val[utility::conversions::to_string_t("meta")]);
    setMeta( newMeta );
    std::shared_ptr<BlockDTO> newBlock(new BlockDTO());
    newBlock->fromJson(val[utility::conversions::to_string_t("block")]);
    setBlock( newBlock );
}

void BlockInfoDTO::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    m_Meta->toMultipart(multipart, utility::conversions::to_string_t("meta."));
    m_Block->toMultipart(multipart, utility::conversions::to_string_t("block."));
}

void BlockInfoDTO::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    std::shared_ptr<BlockMetaDTO> newMeta(new BlockMetaDTO());
    newMeta->fromMultiPart(multipart, utility::conversions::to_string_t("meta."));
    setMeta( newMeta );
    std::shared_ptr<BlockDTO> newBlock(new BlockDTO());
    newBlock->fromMultiPart(multipart, utility::conversions::to_string_t("block."));
    setBlock( newBlock );
}

std::shared_ptr<BlockMetaDTO> BlockInfoDTO::getMeta() const
{
    return m_Meta;
}


void BlockInfoDTO::setMeta(std::shared_ptr<BlockMetaDTO> value)
{
    m_Meta = value;
    
}
std::shared_ptr<BlockDTO> BlockInfoDTO::getBlock() const
{
    return m_Block;
}


void BlockInfoDTO::setBlock(std::shared_ptr<BlockDTO> value)
{
    m_Block = value;
    
}
}
}
}
}

