/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CommunicationTimestamps.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CommunicationTimestamps_H_
#define IO_SWAGGER_CLIENT_MODEL_CommunicationTimestamps_H_


#include "../ModelBase.h"

#include "UInt64DTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CommunicationTimestamps
    : public ModelBase
{
public:
    CommunicationTimestamps();
    virtual ~CommunicationTimestamps();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CommunicationTimestamps members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getSendTimestamp() const;
    bool sendTimestampIsSet() const;
    void unsetSendTimestamp();
    void setSendTimestamp(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getReceiveTimestamp() const;
    bool receiveTimestampIsSet() const;
    void unsetReceiveTimestamp();
    void setReceiveTimestamp(std::shared_ptr<UInt64DTO> value);

protected:
    std::shared_ptr<UInt64DTO> m_SendTimestamp;
    bool m_SendTimestampIsSet;
    std::shared_ptr<UInt64DTO> m_ReceiveTimestamp;
    bool m_ReceiveTimestampIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CommunicationTimestamps_H_ */
