/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Multisig.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Multisig_H_
#define IO_SWAGGER_CLIENT_MODEL_Multisig_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Multisig
    : public ModelBase
{
public:
    Multisig();
    virtual ~Multisig();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Multisig members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAccount() const;
        void setAccount(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAccountAddress() const;
    bool accountAddressIsSet() const;
    void unsetAccountAddress();
    void setAccountAddress(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getMinApproval() const;
        void setMinApproval(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getMinRemoval() const;
        void setMinRemoval(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getCosignatories();
        void setCosignatories(std::vector<utility::string_t> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getMultisigAccounts();
        void setMultisigAccounts(std::vector<utility::string_t> value);

protected:
    utility::string_t m_Account;
        utility::string_t m_AccountAddress;
    bool m_AccountAddressIsSet;
    int32_t m_MinApproval;
        int32_t m_MinRemoval;
        std::vector<utility::string_t> m_Cosignatories;
        std::vector<utility::string_t> m_MultisigAccounts;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Multisig_H_ */
