/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * MultisigAccountGraphInfoDTO.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_MultisigAccountGraphInfoDTO_H_
#define IO_SWAGGER_CLIENT_MODEL_MultisigAccountGraphInfoDTO_H_


#include "../ModelBase.h"

#include "MultisigAccountInfoDTO.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  MultisigAccountGraphInfoDTO
    : public ModelBase
{
public:
    MultisigAccountGraphInfoDTO();
    virtual ~MultisigAccountGraphInfoDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MultisigAccountGraphInfoDTO members

    /// <summary>
    /// 
    /// </summary>
    int32_t getLevel() const;
        void setLevel(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<MultisigAccountInfoDTO>>& getMultisigEntries();
        void setMultisigEntries(std::vector<std::shared_ptr<MultisigAccountInfoDTO>> value);

protected:
    int32_t m_Level;
        std::vector<std::shared_ptr<MultisigAccountInfoDTO>> m_MultisigEntries;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_MultisigAccountGraphInfoDTO_H_ */
