/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * NamespaceInfoDTO.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_NamespaceInfoDTO_H_
#define IO_SWAGGER_CLIENT_MODEL_NamespaceInfoDTO_H_


#include "../ModelBase.h"

#include "NamespaceDTO.h"
#include "NamespaceMosaicMetaDTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  NamespaceInfoDTO
    : public ModelBase
{
public:
    NamespaceInfoDTO();
    virtual ~NamespaceInfoDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NamespaceInfoDTO members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<NamespaceMosaicMetaDTO> getMeta() const;
        void setMeta(std::shared_ptr<NamespaceMosaicMetaDTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<NamespaceDTO> getNamespace() const;
        void setNamespace(std::shared_ptr<NamespaceDTO> value);

protected:
    std::shared_ptr<NamespaceMosaicMetaDTO> m_Meta;
        std::shared_ptr<NamespaceDTO> m__namespace;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_NamespaceInfoDTO_H_ */
