/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * NamespaceDTO.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_NamespaceDTO_H_
#define IO_SWAGGER_CLIENT_MODEL_NamespaceDTO_H_


#include "../ModelBase.h"

#include "UInt64DTO.h"
#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  NamespaceDTO
    : public ModelBase
{
public:
    NamespaceDTO();
    virtual ~NamespaceDTO();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NamespaceDTO members

    /// <summary>
    /// 
    /// </summary>
    int32_t getType() const;
        void setType(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getDepth() const;
        void setDepth(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getLevel0() const;
        void setLevel0(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getLevel1() const;
    bool level1IsSet() const;
    void unsetLevel1();
    void setLevel1(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getLevel2() const;
    bool level2IsSet() const;
    void unsetLevel2();
    void setLevel2(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getParentId() const;
        void setParentId(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOwner() const;
        void setOwner(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOwnerAddress() const;
    bool ownerAddressIsSet() const;
    void unsetOwnerAddress();
    void setOwnerAddress(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getStartHeight() const;
        void setStartHeight(std::shared_ptr<UInt64DTO> value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<UInt64DTO> getEndHeight() const;
        void setEndHeight(std::shared_ptr<UInt64DTO> value);

protected:
    int32_t m_Type;
        int32_t m_Depth;
        std::shared_ptr<UInt64DTO> m_Level0;
        std::shared_ptr<UInt64DTO> m_Level1;
    bool m_Level1IsSet;
    std::shared_ptr<UInt64DTO> m_Level2;
    bool m_Level2IsSet;
    std::shared_ptr<UInt64DTO> m_ParentId;
        utility::string_t m_Owner;
        utility::string_t m_OwnerAddress;
    bool m_OwnerAddressIsSet;
    std::shared_ptr<UInt64DTO> m_StartHeight;
        std::shared_ptr<UInt64DTO> m_EndHeight;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_NamespaceDTO_H_ */
