/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TransactionPayload.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_TransactionPayload_H_
#define IO_SWAGGER_CLIENT_MODEL_TransactionPayload_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  TransactionPayload
    : public ModelBase
{
public:
    TransactionPayload();
    virtual ~TransactionPayload();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TransactionPayload members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPayload() const;
    bool payloadIsSet() const;
    void unsetPayload();
    void setPayload(utility::string_t value);

protected:
    utility::string_t m_Payload;
    bool m_PayloadIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_TransactionPayload_H_ */
