/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TransactionHashes.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_TransactionHashes_H_
#define IO_SWAGGER_CLIENT_MODEL_TransactionHashes_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  TransactionHashes
    : public ModelBase
{
public:
    TransactionHashes();
    virtual ~TransactionHashes();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TransactionHashes members

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getHashes();
    bool hashesIsSet() const;
    void unsetHashes();
    void setHashes(std::vector<utility::string_t> value);

protected:
    std::vector<utility::string_t> m_Hashes;
    bool m_HashesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_TransactionHashes_H_ */
