/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "TransactionPayload.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

TransactionPayload::TransactionPayload()
{
    m_Payload = utility::conversions::to_string_t("");
    m_PayloadIsSet = false;
}

TransactionPayload::~TransactionPayload()
{
}

void TransactionPayload::validate()
{
    // TODO: implement validation
}

web::json::value TransactionPayload::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_PayloadIsSet)
    {
        val[utility::conversions::to_string_t("payload")] = ModelBase::toJson(m_Payload);
    }

    return val;
}

void TransactionPayload::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("payload")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("payload")];
        if(!fieldValue.is_null())
        {
            setPayload(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void TransactionPayload::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_PayloadIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("payload"), m_Payload));
        
    }
}

void TransactionPayload::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("payload")))
    {
        setPayload(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("payload"))));
    }
}

utility::string_t TransactionPayload::getPayload() const
{
    return m_Payload;
}


void TransactionPayload::setPayload(utility::string_t value)
{
    m_Payload = value;
    m_PayloadIsSet = true;
}
bool TransactionPayload::payloadIsSet() const
{
    return m_PayloadIsSet;
}

void TransactionPayload::unsetPayload()
{
    m_PayloadIsSet = false;
}

}
}
}
}

