/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "UInt64DTO.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

UInt64DTO::UInt64DTO()
{
}

UInt64DTO::~UInt64DTO()
{
}

void UInt64DTO::validate()
{
    // TODO: implement validation
}

web::json::value UInt64DTO::toJson() const
{
    web::json::value val = this->null<int32_t>::toJson();


    return val;
}

void UInt64DTO::fromJson(web::json::value& val)
{
    this->null<int32_t>::fromJson(val);

}

void UInt64DTO::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

}

void UInt64DTO::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

}

}
}
}
}

